// Escape special LaTeX characters in user-supplied text
function esc(text) {
  if (!text) return '';
  return String(text)
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/\^/g, '\\textasciicircum{}')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/#/g, '\\#')
    .replace(/\$/g, '\\$')
    .replace(/%/g, '\\%')
    .replace(/&/g, '\\&')
    .replace(/_/g, '\\_')
    .replace(/\{/g, '\\{')
    .replace(/\}/g, '\\}');
}

/**
 * Generates the Jake's Resume LaTeX source (.tex) from a GeneratedResume object.
 * Compile with: pdflatex resume.tex  (or upload to Overleaf – overleaf.com)
 *
 * Jake's Resume is one of the most popular ATS-friendly templates on GitHub.
 * It uses single-column layout, standard Computer Modern fonts, and tabularx
 * for aligned two-column entry headers — all fully text-based and parser-safe.
 */
function generateResumeLatex(resume) {
  const c = resume.contact || {};

  // Build the contact line — use href for URLs / email
  const contactItems = [
    c.phone ? esc(c.phone) : null,
    c.email ? `\\href{mailto:${esc(c.email)}}{\\underline{${esc(c.email)}}}` : null,
    c.location ? esc(c.location) : null,
    c.linkedin ? `\\href{${esc(c.linkedin)}}{\\underline{LinkedIn}}` : null,
    c.github ? `\\href{${esc(c.github)}}{\\underline{GitHub}}` : null,
    c.website ? `\\href{${esc(c.website)}}{\\underline{Portfolio}}` : null,
  ].filter(Boolean);

  // ── Section renderers ─────────────────────────────────────────────────────

  function renderSummary() {
    if (!resume.summary) return '';
    return `
%-----------PROFESSIONAL SUMMARY-----------
\\section{Professional Summary}
  \\small{${esc(resume.summary)}}
`;
  }

  function renderExperience() {
    if (!resume.experience?.length) return '';
    const entries = resume.experience.map(exp => {
      const bullets = (exp.bullets || [])
        .map(b => `        \\resumeItem{${esc(b)}}`)
        .join('\n');
      return `    \\resumeSubheading
      {${esc(exp.title)}}{${esc(exp.period)}}
      {${esc(exp.company)}}{${esc(exp.location)}}
      \\resumeItemListStart
${bullets}
      \\resumeItemListEnd`;
    }).join('\n\n');

    return `
%-----------EXPERIENCE-----------
\\section{Experience}
  \\resumeSubHeadingListStart
${entries}
  \\resumeSubHeadingListEnd
`;
  }

  function renderSkills() {
    if (!resume.skills?.length) return '';
    // Group skills into lines of ~10
    const CHUNK = 10;
    const lines = [];
    for (let i = 0; i < resume.skills.length; i += CHUNK) {
      lines.push(resume.skills.slice(i, i + CHUNK).map(esc).join(', '));
    }
    const skillContent = lines.join('; ');
    return `
%-----------TECHNICAL SKILLS-----------
\\section{Technical Skills}
  \\begin{itemize}[leftmargin=0.15in, label={}]
    \\small{\\item{\\textbf{Skills}{: ${skillContent}}}}
  \\end{itemize}
`;
  }

  function renderProjects() {
    if (!resume.projects?.length) return '';
    const entries = resume.projects.map(proj => {
      const heading = proj.tech
        ? `\\textbf{${esc(proj.name)}} $|$ \\emph{\\small{${esc(proj.tech)}}}`
        : `\\textbf{${esc(proj.name)}}`;
      return `    \\resumeProjectHeading
        {${heading}}{}
      \\resumeItemListStart
        \\resumeItem{${esc(proj.description)}}
      \\resumeItemListEnd`;
    }).join('\n\n');

    return `
%-----------PROJECTS-----------
\\section{Projects}
  \\resumeSubHeadingListStart
${entries}
  \\resumeSubHeadingListEnd
`;
  }

  function renderEducation() {
    if (!resume.education?.length) return '';
    const entries = resume.education.map(ed => `    \\resumeSubheading
      {${esc(ed.institution)}}{${esc(ed.year)}}
      {${esc(ed.degree)}}{}`)
      .join('\n\n');

    return `
%-----------EDUCATION-----------
\\section{Education}
  \\resumeSubHeadingListStart
${entries}
  \\resumeSubHeadingListEnd
`;
  }

  function renderCertifications() {
    if (!resume.certifications?.length) return '';
    const items = resume.certifications
      .map(cert => `      \\resumeItem{${esc(cert)}}`)
      .join('\n');
    return `
%-----------CERTIFICATIONS-----------
\\section{Certifications}
  \\resumeSubHeadingListStart
    \\item
    \\resumeItemListStart
${items}
    \\resumeItemListEnd
  \\resumeSubHeadingListEnd
`;
  }

  // ── Full document ─────────────────────────────────────────────────────────
  return `%% ATS-Friendly Resume — Jake's Resume Template
%% Generated by JobHunt Resume Builder
%% Compile: pdflatex resume.tex  OR  upload to https://overleaf.com
%%
%% Required packages (all included in TeX Live / MiKTeX and available on Overleaf):
%%   latexsym, fullpage, titlesec, marvosym, color, verbatim,
%%   enumitem, hyperref, fancyhdr, babel, tabularx, glyphtounicode

\\documentclass[letterpaper,11pt]{article}

\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\input{glyphtounicode}

\\pagestyle{fancy}
\\fancyhf{}
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

\\addtolength{\\oddsidemargin}{-0.5in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1in}
\\addtolength{\\topmargin}{-.5in}
\\addtolength{\\textheight}{1.0in}

\\urlstyle{same}
\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large
}{}{0em}{}[\\color{black}\\titlerule \\vspace{-5pt}]

\\pdfgentounicode=1

%% ── Custom resume commands ───────────────────────────────────────────────────

\\newcommand{\\resumeItem}[1]{
  \\item\\small{#1 \\vspace{-2pt}}
}

\\newcommand{\\resumeSubheading}[4]{
  \\vspace{-2pt}\\item
    \\begin{tabular*}{0.97\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{#1} & #2 \\\\
      \\textit{\\small#3} & \\textit{\\small #4} \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeProjectHeading}[2]{
  \\item
    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\small#1 & #2 \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\renewcommand\\labelitemii{$\\vcenter{\\hbox{\\tiny$\\bullet$}}$}

\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0.15in, label={}]}
\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}

%% ════════════════════════════════════════════════════════════════════════════
\\begin{document}

%% ── Heading ──────────────────────────────────────────────────────────────────
\\begin{center}
  {\\Huge \\scshape ${esc(resume.name || 'Your Name')}} \\\\[4pt]
  \\small ${contactItems.join(' $|$ ')}
\\end{center}
${renderSummary()}${renderExperience()}${renderSkills()}${renderProjects()}${renderEducation()}${renderCertifications()}
\\end{document}
`;
}

module.exports = { generateResumeLatex };
